### ISSUE TITLE
Technologies

### ISSUE THREAD

**Issue by notoriousb1t** [notoriousb1t/locomation-tools#1]
@shshaw I started with Electron + TypeScript + TypeStyle + VueJS, but after working with it for a day, I realized that VueJS in JSX is kind of a fringe use case for Vue based on its community.  After working in React, the JSX in Vue seemed unnatural.

I went with one of your suggestions and re-scaffolded the tools using electron-vue.  Outside of really aggressive es-linting, it seems to be a good fit for what we are trying to do here.  

I have a working "browser" experience using an iframe and a simple address bar in electron.  At the moment you have to hit go for it to load.

I haven't used Vue outside of naive examples since 0.8.x, so I don't have an opinion on the best solution for state management.  I do think we need unidirectional data flow for this particular application.  

What do you think?

**Comment by shshaw** [comment]
Sarah Drasner's Vue series on CSS Tricks should be a good get-up-to-speed overview for you: https://css-tricks.com/intro-to-vue-1-rendering-directives-events/

One of the parts covers Vuex, Vue's official state management solution. I haven't used it yet on a project but is supposedly quite easy to use, especially compared to Redux: https://css-tricks.com/intro-to-vue-4-vuex/

**Comment by notoriousb1t** [comment]
Thanks for the tip!  I'll give those articles a read.

I saw one other state management lib while I was looking around.  https://github.com/vuejs/vue-rx  It looks like it would be pretty straightforward to setup unidirectional dataflow that way as well

I think we also need to consider undo (1 step backward)

**Comment by shshaw** [comment]
Haven't used RxJS either, so I'm open to either. Depends on how you envision the data being easiest to handle.

**Comment by notoriousb1t** [comment]
I'll research and lay out some options.  Regardless of the state management piece in the iframe/webview and the mainwindow process, it should probably communicate with the host process through ipc rather than attempting to bridge the gap through frames.

**Comment by notoriousb1t** [comment]
Okay, so great read on Vue!  I will try to see if I can get Vuex working on both iframe and mainwindow side and talking through IPC.  If I can't get that to work, I think we should go with redux

**Comment by shshaw** [comment]
I'm not sure that I've run across IPC before, what is it?

**Comment by notoriousb1t** [comment]
It is the messaging system between electron's main process and its renderer processes (browser windows) https://github.com/electron/electron/blob/master/docs/api/ipc-main.md

**Comment by notoriousb1t** [comment]
Basically, every time each environment changed, the renderers would emit that change to the main process which would then broadcast it down so all parties are kept in sync
